version: '3'
services:
  atcoder:
    build: ./
    image: atcoder
    container_name: atcoder
    tty: true
    volumes:
      - ../:/atcoder
      - ./secrets/cookie.jar:/root/.local/share/online-judge-tools/cookie.jar
      - ./secrets/session.json:/root/.config/atcoder-cli-nodejs/session.json
